# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-03-03 11:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='AdminModel',
        ),
    ]
