# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-03-16 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_auto_20170303_1944'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adminmodel',
            table='admin',
        ),
    ]
