# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-30 01:56
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('loginTime', models.DateTimeField()),
                ('root', models.BooleanField(default=False)),
                ('addTime', models.DateTimeField(auto_now_add=True)),
                ('addAdminId', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='CarouselModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('show', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=1)),
                ('imgUrl', models.URLField()),
                ('linkUrl', models.URLField()),
                ('addTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'index_carousel',
            },
        ),
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('nickname', models.CharField(default='unknown', max_length=30)),
                ('mobile', models.CharField(max_length=15, null=True, unique=True)),
                ('email', models.CharField(max_length=30, null=True, unique=True)),
                ('avatar', models.URLField()),
                ('registTime', models.DateTimeField(auto_now_add=True)),
                ('birthday', models.DateField(null=True)),
                ('sex', models.IntegerField(choices=[(1, 'male'), (2, 'female'), (3, 'secret')], default=3)),
                ('level', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='GroupModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('addTime', models.DateTimeField(auto_now_add=True)),
                ('addAdminId', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'admin_group',
            },
        ),
        migrations.CreateModel(
            name='NodeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('controller', models.CharField(max_length=30)),
                ('action', models.CharField(max_length=30)),
                ('linkUrl', models.URLField()),
                ('addTime', models.DateTimeField(auto_now_add=True)),
                ('addAdminId', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'admin_node',
            },
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'unpay'), (2, 'unsend'), (3, 'unreceive'), (4, 'unevaluate'), (5, 'finish'), (6, 'cancel'), (7, 'refund'), (8, 'accept-refund')], default=1)),
                ('addTime', models.DateTimeField(auto_now_add=True)),
                ('payTime', models.DateTimeField(null=True)),
                ('sendTime', models.DateTimeField(null=True)),
                ('receiveTime', models.DateTimeField(null=True)),
                ('evaluateTime', models.DateTimeField(null=True)),
                ('cancelTime', models.DateTimeField(null=True)),
                ('refundTime', models.DateTimeField(null=True)),
                ('ACRefundTime', models.DateTimeField(null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='models.CustomerModel')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addTime', models.DateTimeField(auto_now_add=True)),
                ('sellPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='models.OrderModel')),
            ],
            options={
                'db_table': 'order_product',
            },
        ),
        migrations.CreateModel(
            name='ProductCategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentId', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=1)),
                ('grade', models.IntegerField(default=1)),
                ('show', models.BooleanField(default=True)),
                ('addTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'product_category',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brand', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('soldoutAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('addTime', models.DateTimeField(auto_now_add=True)),
                ('onShelveTime', models.DateTimeField(null=True)),
                ('offShelveTime', models.DateTimeField(null=True)),
                ('description', models.TextField()),
                ('thumbnailLink', models.URLField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='models.ProductCategoryModel')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ReceiveAddressModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=30)),
                ('addTime', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiveAddresses', to='models.CustomerModel')),
            ],
            options={
                'db_table': 'customer_receiveaddress',
            },
        ),
        migrations.CreateModel(
            name='SellerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=130)),
                ('mobile', models.CharField(max_length=11, null=True, unique=True)),
                ('email', models.CharField(max_length=30, null=True, unique=True)),
                ('realname', models.CharField(max_length=30)),
                ('idno', models.CharField(max_length=20, unique=True)),
                ('registTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'seller',
            },
        ),
        migrations.CreateModel(
            name='ShoppingGuideChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('addTime', models.DateTimeField(auto_now_add=True)),
                ('addAdminId', models.IntegerField()),
                ('show', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'shoppingguide_channel',
            },
        ),
        migrations.CreateModel(
            name='ShoppingGuideProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentId', models.IntegerField()),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=100)),
                ('linkUrl', models.URLField(default='')),
                ('productImgUrl', models.URLField(default='')),
                ('addTime', models.DateTimeField(auto_now_add=True)),
                ('addAdminId', models.IntegerField()),
                ('show', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'shoppingguide_product',
            },
        ),
        migrations.CreateModel(
            name='ShoppingGuideSubchannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parentId', models.IntegerField()),
                ('addTime', models.DateTimeField(auto_now_add=True)),
                ('addAdminId', models.IntegerField()),
                ('show', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'shoppingguide_subchannel',
            },
        ),
        migrations.AddField(
            model_name='productmodel',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='models.SellerModel'),
        ),
        migrations.AddField(
            model_name='orderproductmodel',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='models.ProductModel'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='recevieAddress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='models.ReceiveAddressModel'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='models.SellerModel'),
        ),
        migrations.AddField(
            model_name='groupmodel',
            name='nodes',
            field=models.ManyToManyField(related_name='nodes', to='models.NodeModel'),
        ),
        migrations.AddField(
            model_name='adminmodel',
            name='groups',
            field=models.ManyToManyField(related_name='groups', to='models.GroupModel'),
        ),
    ]
