# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-03-29 07:12
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('loginTime', models.DateTimeField()),
                ('root', models.BooleanField(default=False)),
                ('addTime', models.DateTimeField(auto_now_add=True)),
                ('addAdminId', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='CarouselModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('show', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=1)),
                ('imgUrl', models.URLField()),
                ('linkUrl', models.URLField()),
                ('addTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'index_carousel',
            },
        ),
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('nickname', models.CharField(default='unknown', max_length=30)),
                ('mobile', models.CharField(max_length=15, null=True, unique=True)),
                ('email', models.CharField(max_length=30, null=True, unique=True)),
                ('avatar', models.URLField()),
                ('registTime', models.DateTimeField(auto_now_add=True)),
                ('birthday', models.DateField(null=True)),
                ('sex', models.IntegerField(choices=[(1, 'male'), (2, 'female'), (3, 'secret')], default=3)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='GroupModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('addTime', models.DateTimeField(auto_now_add=True)),
                ('addAdminId', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'admin_group',
            },
        ),
        migrations.CreateModel(
            name='NodeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('controller', models.CharField(max_length=30)),
                ('action', models.CharField(max_length=30)),
                ('linkUrl', models.URLField()),
                ('addTime', models.DateTimeField(auto_now_add=True)),
                ('addAdminId', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'admin_node',
            },
        ),
        migrations.CreateModel(
            name='ProductCategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentId', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=1)),
                ('grade', models.IntegerField(default=1)),
                ('show', models.BooleanField(default=True)),
                ('addTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'product_category',
            },
        ),
        migrations.CreateModel(
            name='ReceiveAddressModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=30)),
                ('addTime', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', related_query_name='recevieAddresses', to='models.CustomerModel')),
            ],
            options={
                'db_table': 'customer_receiveaddress',
            },
        ),
        migrations.CreateModel(
            name='ShoppingGuideChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('addTime', models.DateTimeField(auto_now_add=True)),
                ('addAdminId', models.IntegerField()),
                ('show', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'shoppingguide_channel',
            },
        ),
        migrations.CreateModel(
            name='ShoppingGuideProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentId', models.IntegerField()),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=100)),
                ('linkUrl', models.URLField(default='')),
                ('productImgUrl', models.URLField(default='')),
                ('addTime', models.DateTimeField(auto_now_add=True)),
                ('addAdminId', models.IntegerField()),
                ('show', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'shoppingguide_product',
            },
        ),
        migrations.CreateModel(
            name='ShoppingGuideSubchannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parentId', models.IntegerField()),
                ('addTime', models.DateTimeField(auto_now_add=True)),
                ('addAdminId', models.IntegerField()),
                ('show', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'shoppingguide_subchannel',
            },
        ),
        migrations.AddField(
            model_name='groupmodel',
            name='nodes',
            field=models.ManyToManyField(related_name='nodes', to='models.NodeModel'),
        ),
        migrations.AddField(
            model_name='adminmodel',
            name='groups',
            field=models.ManyToManyField(related_name='groups', to='models.GroupModel'),
        ),
    ]
