# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-20 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=130)),
                ('mobile', models.CharField(max_length=30, null=True, unique=True)),
                ('email', models.CharField(max_length=11, null=True, unique=True)),
            ],
        ),
    ]
