# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-03-22 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20170220_1711'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
