# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-03-16 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('show', models.BooleanField(default=False)),
                ('order', models.IntegerField()),
                ('imgUrl', models.URLField()),
                ('linkUrl', models.URLField()),
                ('addTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'index_carousel',
            },
        ),
    ]
