# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-03-16 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselmodel',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
