# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-03-17 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170316_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='productCategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentId', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=1)),
                ('show', models.BooleanField(default=True)),
                ('addTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'commodity_category',
            },
        ),
        migrations.AlterField(
            model_name='carouselmodel',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
