# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-03-17 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170317_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategorymodel',
            name='grade',
            field=models.IntegerField(default=0),
        ),
    ]
